@local = http://localhost:3000


### Criar/
POST {{local}}/api/v1/jogadores
Content-Type: application/json

{
    "nome": "Aurora",
    "email": "aurora@gmail.com",
    "telefoneCelular": "21999889999"
}


### Altrera (_id)
PUT {{local}}/api/v1/jogadores/610feae96797640f1a16a550
Content-Type: application/json

{
    "nome": "Carmen Mattos",
    "telefoneCelular": "21999889999"
}

### Consultar
GET {{local}}/api/v1/jogadores
Content-Type: application/json

{ }


### Consultar/:email
GET {{local}}/api/v1/jogadores?email=wca@gmail.com
Content-Type: application/json

{ }


### deletar/:email
DELETE {{local}}/api/v1/jogadores?email=wca@gmail.com
Content-Type: application/json

{ }