@local = http://localhost:3000


### Criar/Atualizar
POST {{local}}/api/v1/jogadores
Content-Type: application/json

{
    "nome": "Carmen C Mattos ",
    "email": "carmen@gmail.com",
    "telefoneCelular": "21989999999"
}

### Consultar
GET {{local}}/api/v1/jogadores
Content-Type: application/json

{ }


### Consultar/:email
GET {{local}}/api/v1/jogadores?email=wca@gmail.com
Content-Type: application/json

{ }


### deletar/:email
DELETE {{local}}/api/v1/jogadores?email=wca@gmail.com
Content-Type: application/json

{ }