@local = http://localhost:3000/v1/api


### Criar/
POST {{local}}/jogadores
Content-Type: application/json

{
    "nome": "Welington",
    "email": "welington@gmail.com",
    "telefoneCelular": "21999889799"
}


### Altrera (_id)
PUT {{local}}/jogadores/610feae96797640f1a16a550
Content-Type: application/json

{
    "nome": "Carmen Mattos",
    "telefoneCelular": "21999889999"
}

### Consultar
GET {{local}}/jogadores
Content-Type: application/json

{ }


### Consultar/:email
GET {{local}}/jogadores?email=wca@gmail.com
Content-Type: application/json

{ }


### deletar/:email
DELETE {{local}}/jogadores?email=wca@gmail.com
Content-Type: application/json

{ }